name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 特性'
    labels:
      - 'feat'
      - 'feature'
      - 'enhancement'
  - title: '🐛 BUG修复'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 维护'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## 发生了什么变化

  $CHANGES